stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shared
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker compose -p ansiin-task-managers up --build --remove-orphans --detach
