services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - vue-task-manager

  vue-task-manager:
    build:
      context: ./vue-task-manager
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://taltech.akaver.com/api/v1.0
        VITE_APP_BASE_PATH: /vue-task-manager/
    restart: unless-stopped
