<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-WebApp-7bc0e7de-2ef9-4f75-99e8-4d9d09badc92</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.14" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.14">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.BLL\App.BLL.csproj" />
      <ProjectReference Include="..\App.DAL.EF\App.DAL.EF.csproj" />
      <ProjectReference Include="..\App.DTO\App.DTO.csproj" />
      <ProjectReference Include="..\App.Resources\App.Resources.csproj" />
      <ProjectReference Include="..\Base.Helpers\Base.Helpers.csproj" />
    </ItemGroup>

</Project>
